"""Regenerate ``serve.yaml``, seeding the tree with the *current* LLaMAR prompts.

The seed's text fields must be the content the harness actually loads today
(``sar_orch/prompts/coordinator/system.semantic.md`` and
``sar_orch/prompts/worker/system.md``), so a prompt change is re-seeded by
re-running this script rather than hand-editing 25 KB of YAML. The generated
file is parsed back and compared against the config it was built from, so a
formatting mistake can never silently alter a seeded prompt.

Usage::

    python -m reef_sar_adapter.gen_serve_yaml                       # rewrite serve.yaml
    python -m reef_sar_adapter.gen_serve_yaml --check               # exit 1 when stale
    python -m reef_sar_adapter.gen_serve_yaml --repo /path/to/LLaMAR

``--repo`` defaults to this package's repository root (the adapter lives at the
LLaMAR checkout's top level). ``--check`` is what the unit tests run.
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Sequence
from pathlib import Path
from typing import Any

import yaml

from .runner import RULES_PLACEHOLDER

__all__ = [
    "PROMPT_FILES",
    "SERVE_FILE",
    "SMOKE_TASKS",
    "build_serve_yaml",
    "expected_config",
    "main",
    "prompt_texts",
]

#: The file this module owns, beside the package.
SERVE_FILE = Path(__file__).resolve().with_name("serve.yaml")

#: Entry id -> the LLaMAR prompt file its text seeds, relative to the repo root.
PROMPT_FILES: dict[str, str] = {
    "system.semantic": "sar_orch/prompts/coordinator/system.semantic.md",
    "worker-system": "sar_orch/prompts/worker/system.md",
}

#: The smoke task set: scene3 x agents{2,4} x seed{0,10}, 35-step budget.
SMOKE_TASKS: tuple[str, ...] = (
    '{"scene":3,"agents":2,"seed":0,"max_steps":35}',
    '{"scene":3,"agents":2,"seed":10,"max_steps":35}',
    '{"scene":3,"agents":4,"seed":0,"max_steps":35}',
    '{"scene":3,"agents":4,"seed":10,"max_steps":35}',
)


def repo_root() -> Path:
    """The LLaMAR checkout this package lives in (the adapter is at its top level)."""
    return Path(__file__).resolve().parents[1]


def prompt_texts(repo: Path) -> dict[str, str]:
    """The seeded prompt bodies, read from ``repo``; a missing file is an error."""
    texts: dict[str, str] = {}
    for entry_id, relative in PROMPT_FILES.items():
        path = repo / relative
        try:
            texts[entry_id] = path.read_text(encoding="utf-8")
        except OSError as exc:
            raise SystemExit(f"gen_serve_yaml: cannot read {path}: {exc}") from exc
    return texts


def expected_config(repo: Path) -> dict[str, Any]:
    """The config ``serve.yaml`` must hold, as data (the render and the check share it)."""
    prompts = prompt_texts(repo)
    return {
        "implementation": "reef.train.cordis_backend.recipe:CordisRecipe",
        "execution": {"evolution": {"workers": 2}},
        "evolution": {
            "adapter": "sar",
            "propose": "reef_sar_adapter.method:propose",
            "evaluate": "reef_sar_adapter.method:evaluate",
            "tasks": list(SMOKE_TASKS),
            "episode_timeout_s": 1800,
            "episode_repeats": 1,
            "min_win_margin": 0,
            "publish": "review",
            "executor": "local",
            "step_record_dir": "work/step-records",
            "seed": [
                {
                    "id": "system.semantic",
                    "name": "agent_command",
                    "config": {"name": "system.semantic", "text": prompts["system.semantic"]},
                },
                {
                    "id": "worker-system",
                    "name": "skill",
                    "config": {"name": "system", "text": prompts["worker-system"]},
                },
                {"id": "base-rules", "name": "rules", "config": {"text": RULES_PLACEHOLDER}},
                {"id": "sar_config", "name": "config", "config": {"target": "primary", "data": {}}},
            ],
        },
        "data": {"training_mode": "manual", "batch_size": 1},
    }


def build_serve_yaml(repo: Path) -> str:
    """The ``serve.yaml`` text for ``repo``'s current prompts (verified on build)."""
    prompts = prompt_texts(repo)
    lines: list[str] = [
        "# The sar recipe preset for reef's harness evolution (`reef serve -c` reads a",
        "# deployment config that names this preset; see the A3 card for the stack file).",
        "#",
        "# This file is generated by `python -m reef_sar_adapter.gen_serve_yaml`: the",
        "# seed's text fields are the LLaMAR prompts as they are right now, and the",
        "# generator refuses to write a file it cannot parse back to the same config.",
        "#",
        "# Preset YAML is read as-is - `${VAR}` is NOT interpolated here, so every value",
        "# is literal. The seed is the first-boot tree; a recovered tree state wins over it.",
        "",
        "implementation: reef.train.cordis_backend.recipe:CordisRecipe",
        "",
        "# Two episode workers, the benchmark's precedent (B6); one step is 2 x 4",
        "# episodes (candidate + current, one per task), so this runs two at a time.",
        "execution:",
        "  evolution:",
        "    workers: 2",
        "",
        "evolution:",
        "  adapter: sar",
        "  propose: reef_sar_adapter.method:propose",
        "  evaluate: reef_sar_adapter.method:evaluate",
        "  # The smoke suite: scene3 x agents{2,4} x seed{0,10}, 35-step budget.",
        "  # One step runs each task twice - once for the candidate, once for the",
        "  # current tree - and the verdict is wins - losses > min_win_margin.",
        "  tasks:",
    ]
    for task in SMOKE_TASKS:
        lines.append(f"    - '{task}'")
    lines += [
        "  # A full SAR run is minutes of wall clock; the timeout is the backstop.",
        "  episode_timeout_s: 1800",
        "  episode_repeats: 1",
        "  # smoke: 0 (noise-tolerant, it validates the loop, not an improvement);",
        "  # the formal suite raises it so a random win is not published (P3/P6).",
        "  min_win_margin: 0",
        "  # Never publish without a person: promote is the one manual checkpoint.",
        "  publish: review",
        "  # SAR opens ports and needs the LLaMAR venv; the bubblewrap sandbox cannot host it.",
        "  executor: local",
        "  # Every step's proposer calls, parsed proposal and gate episodes land here.",
        "  step_record_dir: work/step-records",
        "  seed:",
        "    # The mutation surface is four entries (B7-1): the coordinator keeps one",
        "    # prompt (the gate always runs mode=semantic), the worker one, plus the",
        "    # rules text and the harness config. The entry ids are what a proposal",
        "    # anchors to (reef_sar_adapter.method.ANCHORS).",
        "    - id: system.semantic",
        "      name: agent_command",
        "      config:",
        "        name: system.semantic",
        "        text: " + _literal_block(prompts["system.semantic"], content_indent=10, key_indent=8),
        "    # The entry id is the tree's storage key; the node name is the render path",
        "    # segment (overlay/prompts/worker/{name}.md), so it stays 'system'.",
        "    - id: worker-system",
        "      name: skill",
        "      config:",
        "        name: system",
        "        text: " + _literal_block(prompts["worker-system"], content_indent=10, key_indent=8),
        "    # Appended to the coordinator's system prompt. The seed carries the",
        "    # runner's baseline placeholder instead of an empty text: reef's rules",
        "    # node refuses an empty 'text' (nodes.py rules_node -> _require_text)",
        "    # and a scenario cannot even be created from such a seed, while the",
        "    # runner appends nothing for the placeholder - the baseline stays",
        "    # byte-identical to the checkout, and a proposal that writes real",
        "    # rules replaces it.",
        "    - id: base-rules",
        "      name: rules",
        '      config: {text: "' + RULES_PLACEHOLDER + '"}',
        "    # The harness config the runner reads: the model binding is injected by",
        "    # reef at episode render, so the tree carries run parameters only.",
        "    - id: sar_config",
        "      name: config",
        "      config:",
        "        target: primary",
        "        data: {}",
        "",
        "data:",
        "  # An operator instruction owns each step (POST /reef/train -> requests[0]);",
        "  # automatic batching stays off, and one instruction is one step.",
        "  training_mode: manual",
        "  batch_size: 1",
        "",
    ]
    text = "\n".join(lines)
    _verify(text, repo)
    return text


def _literal_block(text: str, *, content_indent: int, key_indent: int) -> str:
    """``text`` as a YAML literal block scalar, indented and round-trip safe.

    The block keeps one trailing newline (clip chomping), the shape a prompt
    file has. When the first non-empty line starts with a space, the header
    carries an explicit indentation indicator: auto-detection would otherwise
    read that line's own indentation as the block's.
    """
    lines = text.split("\n")
    if lines and lines[-1] == "":
        lines = lines[:-1]  # the file's final newline is the block's chomping, not content
    first = next((line for line in lines if line.strip()), "")
    header = "|" if not first.startswith((" ", "\t")) else f"|{content_indent - key_indent}"
    pad = " " * content_indent
    body = "\n".join("" if line == "" else pad + line for line in lines)
    return f"{header}\n{body}\n"


def _verify(text: str, repo: Path) -> None:
    """Parse the rendered text back and refuse any drift from the built config."""
    parsed = yaml.safe_load(text)
    expected = expected_config(repo)
    if parsed != expected:
        raise SystemExit("gen_serve_yaml: generated YAML does not parse back to the expected config")


def main(argv: Sequence[str] | None = None) -> int:
    """Rewrite ``serve.yaml``; with ``--check``, report staleness instead."""
    parser = argparse.ArgumentParser(prog="python -m reef_sar_adapter.gen_serve_yaml", description=__doc__)
    parser.add_argument("--repo", default=None, help="the LLaMAR checkout to read prompts from")
    parser.add_argument("--check", action="store_true", help="exit 1 when serve.yaml is out of date")
    args = parser.parse_args(argv)

    repo = Path(args.repo).resolve() if args.repo else repo_root()
    rendered = build_serve_yaml(repo)
    if args.check:
        current = SERVE_FILE.read_text(encoding="utf-8") if SERVE_FILE.is_file() else ""
        if current == rendered:
            print(f"gen_serve_yaml: {SERVE_FILE} is in sync with {repo}")
            return 0
        print(f"gen_serve_yaml: {SERVE_FILE} is stale; re-run without --check", file=sys.stderr)
        return 1
    SERVE_FILE.write_text(rendered, encoding="utf-8")
    print(f"gen_serve_yaml: wrote {SERVE_FILE} ({len(rendered)} chars) from {repo}")
    return 0


if __name__ == "__main__":  # pragma: no cover - module invocation
    raise SystemExit(main())
