"""MCP tool loader with real MCP client integration and timeout handling."""

import asyncio
import json
from contextlib import AsyncExitStack
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal

from mcp import ClientSession, StdioServerParameters
from mcp.client.sse import sse_client
from mcp.client.stdio import stdio_client
from mcp.client.streamable_http import streamablehttp_client

from .base import Tool, ToolResult

# Connection type aliases
ConnectionType = Literal["stdio", "sse", "http", "streamable_http"]


@dataclass
class MCPTimeoutConfig:
    """MCP timeout configuration."""

    connect_timeout: float = 10.0  # Connection timeout (seconds)
    execute_timeout: float = 60.0  # Tool execution timeout (seconds)
    sse_read_timeout: float = 120.0  # SSE read timeout (seconds)
    # Bounded retry budget for the initial handshake.  Workers connect to the
    # coordinator's MCP mount at process startup, which can race the
    # coordinator's ASGI startup: a single refused attempt used to abort the
    # worker for the whole run, so every attempt is retried with an
    # exponential backoff ((``connect_attempts`` total tries, ``retry_backoff``
    # seconds base delay, doubled per retry).
    connect_attempts: int = 3
    retry_backoff: float = 1.0


# Global default timeout config
_default_timeout_config = MCPTimeoutConfig()


def set_mcp_timeout_config(
    connect_timeout: float | None = None,
    execute_timeout: float | None = None,
    sse_read_timeout: float | None = None,
    connect_attempts: int | None = None,
    retry_backoff: float | None = None,
) -> None:
    """Set global MCP timeout configuration.

    Args:
        connect_timeout: Connection timeout in seconds
        execute_timeout: Tool execution timeout in seconds
        sse_read_timeout: SSE read timeout in seconds
        connect_attempts: Total handshake attempts per server (>= 1)
        retry_backoff: Base retry delay in seconds (doubles per retry)
    """
    global _default_timeout_config
    if connect_timeout is not None:
        _default_timeout_config.connect_timeout = connect_timeout
    if execute_timeout is not None:
        _default_timeout_config.execute_timeout = execute_timeout
    if sse_read_timeout is not None:
        _default_timeout_config.sse_read_timeout = sse_read_timeout
    if connect_attempts is not None:
        _default_timeout_config.connect_attempts = max(1, int(connect_attempts))
    if retry_backoff is not None:
        _default_timeout_config.retry_backoff = max(0.0, float(retry_backoff))


def get_mcp_timeout_config() -> MCPTimeoutConfig:
    """Get current MCP timeout configuration."""
    return _default_timeout_config


class MCPConnectError(RuntimeError):
    """An MCP server could not be reached within its retry budget.

    Raised by ``load_mcp_tools_async(..., strict=True)`` so a caller whose
    startup depends on the server (SAR workers need the Map Agent tools) can
    fail loudly instead of silently running without them.
    """

    def __init__(
        self,
        server_name: str,
        target: str,
        attempts: int,
        last_error: BaseException | None,
    ):
        self.server_name = server_name
        self.target = target
        self.attempts = attempts
        self.last_error = last_error
        detail = (
            f"{type(last_error).__name__}: {last_error}"
            if last_error is not None
            else "unknown error"
        )
        super().__init__(
            f"MCP server '{server_name}' ({target}) unreachable after "
            f"{attempts} attempt(s); last error: {detail}"
        )


# anyio tags every cancellation it delivers through a cancel scope with this
# message prefix (see anyio._backends._asyncio.is_anyio_cancellation).
_ANYIO_CANCEL_PREFIX = "Cancelled via cancel scope"


def _is_scope_cancellation(exc: asyncio.CancelledError) -> bool:
    """True when *exc* was generated by a library cancel scope.

    The MCP client transports run inside anyio task groups.  When a transport
    fails (refused connection, aborted handshake, ...) the group tears down by
    cancelling its surrounding scope, so a ``CancelledError`` surfaces in
    ``connect()`` even though nobody cancelled *us*.  anyio marks such
    cancellations with a ``Cancelled via cancel scope <id>`` message and may
    re-raise them from a new exception, hence the ``__context__`` walk
    (mirrors anyio's own ``is_anyio_cancellation`` check).
    """
    while True:
        args = exc.args
        if args and isinstance(args[0], str) and args[0].startswith(_ANYIO_CANCEL_PREFIX):
            return True
        context = exc.__context__
        if isinstance(context, asyncio.CancelledError):
            exc = context
            continue
        return False


def _must_propagate(exc: BaseException) -> bool:
    """True when *exc* has to be re-raised untouched by connection handling.

    Ordinary failures — refused connections, timeouts, HTTP errors, and
    (base) exception groups built from them — are connect failures.
    A ``CancelledError`` that was *not* produced by a library cancel scope is
    a real cancellation of the caller's task (``task.cancel()``) and must
    never be swallowed; the same holds for any other non-``Exception``
    BaseException such as ``KeyboardInterrupt``.
    """
    # Exception groups (3.11+) carry their members in ``exceptions``; looked up
    # dynamically so the module stays importable on the declared 3.10 floor.
    members = getattr(exc, "exceptions", None)
    if isinstance(members, tuple) and all(
        isinstance(member, BaseException) for member in members
    ):
        return any(_must_propagate(member) for member in members)
    if isinstance(exc, asyncio.CancelledError):
        return not _is_scope_cancellation(exc)
    return not isinstance(exc, Exception)


class MCPTool(Tool):
    """Wrapper for MCP tools with timeout handling."""

    def __init__(
        self,
        name: str,
        description: str,
        parameters: dict[str, Any],
        session: ClientSession,
        execute_timeout: float | None = None,
    ):
        self._name = name
        self._description = description
        self._parameters = parameters
        self._session = session
        self._execute_timeout = execute_timeout

    @property
    def name(self) -> str:
        return self._name

    @property
    def description(self) -> str:
        return self._description

    @property
    def parameters(self) -> dict[str, Any]:
        return self._parameters

    async def execute(self, **kwargs) -> ToolResult:
        """Execute MCP tool via the session with timeout protection."""
        timeout = self._execute_timeout or _default_timeout_config.execute_timeout

        try:
            # Wrap call_tool with timeout
            async with asyncio.timeout(timeout):
                result = await self._session.call_tool(self._name, arguments=kwargs)

            # MCP tool results are a list of content items
            content_parts = []
            for item in result.content:
                if hasattr(item, "text"):
                    content_parts.append(item.text)
                else:
                    content_parts.append(str(item))

            content_str = "\n".join(content_parts)

            is_error = result.isError if hasattr(result, "isError") else False

            return ToolResult(
                success=not is_error,
                content=content_str,
                error=None if not is_error else "Tool returned error",
            )

        except TimeoutError:
            return ToolResult(
                success=False,
                content="",
                error=f"MCP tool execution timed out after {timeout}s. The remote server may be slow or unresponsive.",
            )
        except Exception as e:
            return ToolResult(
                success=False, content="", error=f"MCP tool execution failed: {str(e)}"
            )


class MCPServerConnection:
    """Manages connection to a single MCP server (STDIO or URL-based) with timeout handling."""

    def __init__(
        self,
        name: str,
        connection_type: ConnectionType = "stdio",
        # STDIO params
        command: str | None = None,
        args: list[str] | None = None,
        env: dict[str, str] | None = None,
        # URL-based params
        url: str | None = None,
        headers: dict[str, str] | None = None,
        # Timeout overrides (per-server)
        connect_timeout: float | None = None,
        execute_timeout: float | None = None,
        sse_read_timeout: float | None = None,
        # Handshake retry overrides (per-server)
        connect_attempts: int | None = None,
        retry_backoff: float | None = None,
    ):
        self.name = name
        self.connection_type = connection_type
        # STDIO
        self.command = command
        self.args = args or []
        self.env = env or {}
        # URL-based
        self.url = url
        self.headers = headers or {}
        # Timeout settings (per-server overrides)
        self.connect_timeout = connect_timeout
        self.execute_timeout = execute_timeout
        self.sse_read_timeout = sse_read_timeout
        self.connect_attempts = connect_attempts
        self.retry_backoff = retry_backoff
        # Connection state
        self.session: ClientSession | None = None
        self.exit_stack: AsyncExitStack | None = None
        self.tools: list[MCPTool] = []
        #: Failure of the most recent unsuccessful connect() (None after a
        #: successful handshake); surfaced by strict loaders.
        self.last_error: BaseException | None = None
        #: Handshake attempts spent by the most recent connect() call.
        self.last_attempts: int = 0

    def _get_connect_timeout(self) -> float:
        """Get effective connect timeout."""
        return self.connect_timeout or _default_timeout_config.connect_timeout

    def _get_connect_attempts(self) -> int:
        """Get effective number of handshake attempts (>= 1)."""
        configured = (
            self.connect_attempts
            if self.connect_attempts is not None
            else _default_timeout_config.connect_attempts
        )
        return max(1, int(configured))

    def _get_retry_backoff(self) -> float:
        """Get effective base retry delay in seconds."""
        configured = (
            self.retry_backoff
            if self.retry_backoff is not None
            else _default_timeout_config.retry_backoff
        )
        return max(0.0, float(configured))

    def _get_sse_read_timeout(self) -> float:
        """Get effective SSE read timeout."""
        return self.sse_read_timeout or _default_timeout_config.sse_read_timeout

    def _get_execute_timeout(self) -> float:
        """Get effective execute timeout."""
        return self.execute_timeout or _default_timeout_config.execute_timeout

    async def _discard_connection(self) -> None:
        """Drop the transport of an unsuccessful attempt.

        Teardown of an MCP transport runs through the client's anyio task
        group: when the attempt already failed, closing it can raise
        cancellation / exception-group artifacts that are pure noise.  Those
        are logged and dropped; a genuine cancellation still propagates (see
        ``_must_propagate``).
        """
        stack, self.exit_stack = self.exit_stack, None
        self.session = None
        if stack is None:
            return
        try:
            await stack.aclose()
        except BaseException as exc:  # classified by _must_propagate below
            if _must_propagate(exc):
                raise
            print(
                f"  (cleanup of MCP server '{self.name}' raised "
                f"{type(exc).__name__}: {exc}; ignored)"
            )

    async def _connect_once(self) -> None:
        """Run one complete handshake attempt.

        Raises whatever the transport/session raises (including library
        cancellation artifacts); success leaves a live session and the loaded
        tool list on ``self``.
        """
        self.exit_stack = AsyncExitStack()
        connect_timeout = self._get_connect_timeout()

        async with asyncio.timeout(connect_timeout):
            if self.connection_type == "stdio":
                read_stream, write_stream = await self._connect_stdio()
            elif self.connection_type == "sse":
                read_stream, write_stream = await self._connect_sse()
            else:  # http / streamable_http
                read_stream, write_stream = await self._connect_streamable_http()

            # Enter client session context
            session = await self.exit_stack.enter_async_context(
                ClientSession(read_stream, write_stream)
            )
            self.session = session

            # Initialize the session
            await session.initialize()

            # List available tools
            tools_list = await session.list_tools()

        # Wrap each tool with execute timeout
        execute_timeout = self._get_execute_timeout()
        loaded_tools = []
        for tool in tools_list.tools:
            parameters = tool.inputSchema if hasattr(tool, "inputSchema") else {}
            loaded_tools.append(
                MCPTool(
                    name=tool.name,
                    description=tool.description or "",
                    parameters=parameters,
                    session=session,
                    execute_timeout=execute_timeout,
                )
            )
        self.tools = loaded_tools

        conn_info = self.url if self.url else self.command
        print(
            f"✓ Connected to MCP server '{self.name}' ({self.connection_type}: {conn_info}) - loaded {len(self.tools)} tools"
        )
        for tool in self.tools:
            desc = (
                tool.description[:60]
                if len(tool.description) > 60
                else tool.description
            )
            print(f"  - {tool.name}: {desc}...")

    async def connect(self) -> bool:
        """Connect to the MCP server: bounded retries, then an explicit failure.

        Every attempt gets its own ``connect_timeout``; failed attempts are
        retried with an exponential backoff (``connect_attempts`` total tries,
        ``retry_backoff`` base delay).

        Returns ``True`` once the session is initialized and the tool list is
        loaded, ``False`` when every attempt failed (``self.last_error`` keeps
        the final failure for the caller to report).

        Cancellation semantics: a ``CancelledError`` produced by the MCP
        client's own anyio task group (an aborted handshake) is a failed
        attempt like any other; a cancellation of *this* task
        (``task.cancel()``) is re-raised untouched.
        """
        attempts = self._get_connect_attempts()
        backoff = self._get_retry_backoff()
        self.last_attempts = 0

        for attempt in range(1, attempts + 1):
            self.last_attempts = attempt
            try:
                await self._connect_once()
            except BaseException as exc:  # classified by _must_propagate below
                if _must_propagate(exc):
                    await self._discard_connection()
                    raise
                self.last_error = exc
                await self._discard_connection()
                print(
                    f"✗ MCP server '{self.name}' connect attempt "
                    f"{attempt}/{attempts} failed: {type(exc).__name__}: {exc}"
                )
                if attempt < attempts:
                    delay = backoff * (2 ** (attempt - 1))
                    if delay > 0:
                        await asyncio.sleep(delay)
                continue
            self.last_error = None
            return True

        print(
            f"✗ MCP server '{self.name}': giving up after {attempts} attempt(s) "
            f"(last error: {type(self.last_error).__name__}: {self.last_error})"
        )
        return False

    async def _connect_stdio(self):
        """Connect via STDIO transport."""
        server_params = StdioServerParameters(
            command=self.command, args=self.args, env=self.env if self.env else None
        )
        return await self.exit_stack.enter_async_context(stdio_client(server_params))

    async def _connect_sse(self):
        """Connect via SSE transport with timeout parameters."""
        connect_timeout = self._get_connect_timeout()
        sse_read_timeout = self._get_sse_read_timeout()

        return await self.exit_stack.enter_async_context(
            sse_client(
                url=self.url,
                headers=self.headers if self.headers else None,
                timeout=connect_timeout,
                sse_read_timeout=sse_read_timeout,
            )
        )

    async def _connect_streamable_http(self):
        """Connect via Streamable HTTP transport with timeout parameters."""
        connect_timeout = self._get_connect_timeout()
        sse_read_timeout = self._get_sse_read_timeout()

        # streamablehttp_client returns (read, write, get_session_id)
        read_stream, write_stream, _ = await self.exit_stack.enter_async_context(
            streamablehttp_client(
                url=self.url,
                headers=self.headers if self.headers else None,
                timeout=connect_timeout,
                sse_read_timeout=sse_read_timeout,
            )
        )
        return read_stream, write_stream

    async def disconnect(self):
        """Properly disconnect from the MCP server.

        Transport teardown goes through the MCP client's anyio task group;
        when the transport already failed, closing it can raise cancellation /
        exception-group artifacts.  Those are logged and dropped so shutdown
        never crashes on them; a genuine cancellation still propagates.
        """
        stack, self.exit_stack = self.exit_stack, None
        self.session = None
        if stack is None:
            return
        try:
            await stack.aclose()
        except BaseException as exc:  # classified by _must_propagate below
            if _must_propagate(exc):
                raise
            print(
                f"  (disconnect of MCP server '{self.name}' raised "
                f"{type(exc).__name__}: {exc}; ignored)"
            )


# Global connections registry
_mcp_connections: list[MCPServerConnection] = []


def _determine_connection_type(server_config: dict) -> ConnectionType:
    """Determine connection type from server config."""
    explicit_type = server_config.get("type", "").lower()
    if explicit_type in ("stdio", "sse", "http", "streamable_http"):
        return explicit_type
    # Auto-detect: if url exists, default to streamable_http; otherwise stdio
    if server_config.get("url"):
        return "streamable_http"
    return "stdio"


def _resolve_mcp_config_path(config_path: str) -> Path | None:
    """
    Resolve MCP config path with fallback logic.

    Priority:
    1. If the specified path exists, use it
    2. If mcp.json doesn't exist, try mcp-example.json in the same directory
    3. Return None if no config found

    Args:
        config_path: User-specified config path

    Returns:
        Resolved Path object or None if not found
    """
    config_file = Path(config_path)

    # If specified path exists, use it directly
    if config_file.exists():
        return config_file

    # Fallback: if looking for mcp.json, try mcp-example.json
    if config_file.name == "mcp.json":
        example_file = config_file.parent / "mcp-example.json"
        if example_file.exists():
            print(f"mcp.json not found, using template: {example_file}")
            return example_file

    return None


async def load_mcp_tools_async(
    config_path: str = "mcp.json",
    *,
    connection_registry: list[MCPServerConnection] | None = None,
    strict: bool = False,
) -> list[Tool]:
    """
    Load MCP tools from config file.

    This function:
    1. Reads the MCP config file (with fallback to mcp-example.json)
    2. Connects to each server (STDIO or URL-based)
    3. Fetches tool definitions
    4. Wraps them as Tool objects

    Supported config formats:
    - STDIO: {"command": "...", "args": [...], "env": {...}}
    - URL-based: {"url": "https://...", "type": "sse|http|streamable_http", "headers": {...}}

    Per-server timeout overrides (optional):
    - "connect_timeout": float - Connection timeout in seconds
    - "execute_timeout": float - Tool execution timeout in seconds
    - "sse_read_timeout": float - SSE read timeout in seconds
    - "connect_attempts": int   - Total handshake attempts (default 3)
    - "retry_backoff": float    - Base retry delay in seconds (default 1.0)

    Note:
    - If mcp.json is not found, will automatically fallback to mcp-example.json
    - User-specific mcp.json should be created by copying mcp-example.json

    Args:
        config_path: Path to MCP configuration file (default: "mcp.json")
        connection_registry: Registry that owns the created connections
        strict: When True, a server that cannot be reached raises
            ``MCPConnectError`` instead of being skipped.  Callers whose
            startup depends on the server (SAR workers need the Map Agent
            tools) use this to fail loudly rather than run degraded.

    Returns:
        List of Tool objects representing MCP tools

    Raises:
        MCPConnectError: only when ``strict=True`` and a server failed to
            connect within its retry budget.
    """
    config_file = _resolve_mcp_config_path(config_path)

    if config_file is None:
        print(f"MCP config not found: {config_path}")
        return []

    try:
        with open(config_file, encoding="utf-8") as f:
            config = json.load(f)

        mcp_servers = config.get("mcpServers", {})

        if not mcp_servers:
            print("No MCP servers configured")
            return []

        all_tools = []
        registry = (
            _mcp_connections if connection_registry is None else connection_registry
        )
        connect_failures: list[MCPConnectError] = []

        # Connect to each enabled server
        for server_name, server_config in mcp_servers.items():
            if server_config.get("disabled", False):
                print(f"Skipping disabled server: {server_name}")
                continue

            conn_type = _determine_connection_type(server_config)
            url = server_config.get("url")
            command = server_config.get("command")

            # Validate config
            if conn_type == "stdio" and not command:
                print(f"No command specified for STDIO server: {server_name}")
                continue
            if conn_type in ("sse", "http", "streamable_http") and not url:
                print(f"No url specified for {conn_type.upper()} server: {server_name}")
                continue

            connection = MCPServerConnection(
                name=server_name,
                connection_type=conn_type,
                command=command,
                args=server_config.get("args", []),
                env=server_config.get("env", {}),
                url=url,
                headers=server_config.get("headers", {}),
                # Per-server timeout overrides from mcp.json
                connect_timeout=server_config.get("connect_timeout"),
                execute_timeout=server_config.get("execute_timeout"),
                sse_read_timeout=server_config.get("sse_read_timeout"),
                connect_attempts=server_config.get("connect_attempts"),
                retry_backoff=server_config.get("retry_backoff"),
            )
            success = await connection.connect()

            if success:
                registry.append(connection)
                all_tools.extend(connection.tools)
            else:
                connect_failures.append(
                    MCPConnectError(
                        server_name=server_name,
                        target=url or command or "",
                        attempts=connection.last_attempts,
                        last_error=connection.last_error,
                    )
                )

        if connect_failures and strict:
            raise connect_failures[0]

        print(f"\nTotal MCP tools loaded: {len(all_tools)}")

        return all_tools

    except MCPConnectError:
        # Strict-mode connect failure: propagate the typed error instead of
        # letting the generic config handler swallow it into an empty list.
        raise
    except Exception as e:
        print(f"Error loading MCP config: {e}")
        import traceback

        traceback.print_exc()
        return []


async def cleanup_mcp_connections(
    connection_registry: list[MCPServerConnection] | None = None,
):
    """Clean up only the supplied registry, or the legacy global registry."""
    registry = _mcp_connections if connection_registry is None else connection_registry
    for connection in list(registry):
        await connection.disconnect()
    registry.clear()
