coordinator:
  prompts_dir: "src/prompts/coordinator"
  tools_dir: "src/tools/coordinator"
  skills_dir: "src/skills/coordinator"
  log_dir: "logs/agent/coordinator"

worker:
  prompts_dir: "src/prompts/worker"
  tools_dir: null
  skills_dir: null
  log_dir: "logs/agent/worker"

sar_coordinator:
  prompts_dir: "sar_orch/prompts/coordinator"
  tools_dir: "sar_orch/tools/coordinator"
  skills_dir: null
  log_dir: "logs/agent/sar_coordinator"

sar_worker:
  prompts_dir: "sar_orch/prompts/worker"
  tools_dir: "sar_orch/tools/worker"
  skills_dir: null
  log_dir: "logs/agent/sar_worker"
