"""HMAC-based proof for authenticated /team-status requests (Phase 5).

Proof format v2 (URL-safe base64):
    ``worker_id.timestamp.nonce.hmac_hex``

Where ``hmac = HMAC-SHA256(coordinator_secret, "worker_id.timestamp.nonce")``.

Verification checks:
- worker_id matches expected caller
- Timestamp is within max_age and not in the future beyond clock_skew
- HMAC is valid
- Nonce has not been used before within the TTL window (server-side replay guard)

Replay prevention uses a bounded TTL ``UsedNonceStore`` inside the server that
remembers spent nonces for ``max_age_seconds + EVICTION_SLACK``.  The nonce
is a cryptographically random 16-byte hex string generated by the caller.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import secrets
import time

DEFAULT_MAX_AGE_SECONDS = 60
DEFAULT_CLOCK_SKEW_SECONDS = 10
NONCE_BYTES = 16
EVICTION_SLACK = 10
SEPARATOR = "."


class UsedNonceStore:
    """Bounded TTL store of spent proof nonces.

    Thread-safe for asyncio single-event-loop access.  Entries are
    lazily evicted on ``check_and_add()`` calls.  ``_used`` maps
    ``nonce_hex -> expiry_timestamp``.
    """

    def __init__(self, ttl_seconds: int = DEFAULT_MAX_AGE_SECONDS + EVICTION_SLACK):
        self._ttl = ttl_seconds
        self._used: dict[str, float] = {}

    def check_and_add(self, nonce_hex: str) -> bool:
        """Return True if *nonce_hex* is fresh (not seen before within TTL)."""
        now = time.monotonic()
        self._evict(now)
        if nonce_hex in self._used:
            return False
        self._used[nonce_hex] = now + self._ttl
        return True

    def _evict(self, now: float) -> None:
        stale = [k for k, expiry in self._used.items() if expiry <= now]
        for k in stale:
            del self._used[k]

    def __len__(self) -> int:
        return len(self._used)


class TeamStatusProof:
    """Generate and verify HMAC-based /team-status request proof.

    Proof format v2 (URL-safe base64):
        ``worker_id.timestamp.nonce.hmac_hex``

    The nonce is a random 16-byte hex string that makes each proof unique.
    Servers must verify nonce uniqueness via a ``UsedNonceStore``.
    """

    @staticmethod
    def generate(
        coordinator_secret: bytes,
        worker_id: str,
        timestamp: int | None = None,
        nonce: str | None = None,
    ) -> str:
        """Generate a nonce-backed HMAC proof bound to *worker_id*.

        Args:
            coordinator_secret: Shared secret for HMAC.
            worker_id: The requesting worker's ID.
            timestamp: Unix epoch seconds (default: ``time.time()``).
            nonce: 32-char hex string (default: random 16 bytes).

        Returns:
            URL-safe base64-encoded proof string.
        """
        if not coordinator_secret:
            raise ValueError("coordinator_secret must be non-empty")
        if not worker_id:
            raise ValueError("worker_id must be non-empty")
        if timestamp is None:
            timestamp = int(time.time())
        if nonce is None:
            nonce = secrets.token_hex(NONCE_BYTES)
        payload = f"{worker_id}{SEPARATOR}{timestamp}{SEPARATOR}{nonce}".encode()
        sig = hmac.new(coordinator_secret, payload, hashlib.sha256).hexdigest()
        combined = (
            f"{worker_id}{SEPARATOR}{timestamp}{SEPARATOR}{nonce}{SEPARATOR}{sig}"
        )
        return base64.urlsafe_b64encode(combined.encode("utf-8")).decode("ascii")

    @staticmethod
    def verify(
        coordinator_secret: bytes,
        proof: str,
        expected_worker_id: str,
        max_age_seconds: int = DEFAULT_MAX_AGE_SECONDS,
        clock_skew: int = DEFAULT_CLOCK_SKEW_SECONDS,
        nonce_store: UsedNonceStore | None = None,
    ) -> tuple[bool, str]:
        """Verify *proof* for *expected_worker_id*.

        Args:
            coordinator_secret: Shared secret for HMAC.
            proof: URL-safe base64-encoded proof from ``generate()``.
            expected_worker_id: The worker ID to bind against.
            max_age_seconds: Maximum proof age from timestamp.
            clock_skew: Allowed future-timestamp skew.
            nonce_store: Optional ``UsedNonceStore`` for replay
                prevention.  When provided, the nonce must not have been
                seen within its TTL.

        Returns:
            ``(is_valid, reason)`` — reason is empty on success.
        """
        if not coordinator_secret:
            return False, "coordinator_secret is empty"
        if not proof:
            return False, "proof is empty"
        try:
            decoded = base64.urlsafe_b64decode(proof.encode("ascii")).decode("utf-8")
        except (ValueError, Exception) as exc:
            return False, f"base64 decode failed: {exc}"

        parts = decoded.split(SEPARATOR)
        if len(parts) != 4:
            return False, "malformed proof: expected 4 parts (v2 format)"

        worker_id, timestamp_str, nonce, sig_hex = parts
        if worker_id != expected_worker_id:
            return False, "worker_id mismatch"

        try:
            ts = int(timestamp_str)
        except ValueError:
            return False, "invalid timestamp (non-integer)"

        now = int(time.time())
        if now < ts - clock_skew:
            return False, "timestamp in future (clock skew)"
        if now > ts + max_age_seconds:
            return False, "proof expired"

        payload = f"{worker_id}{SEPARATOR}{timestamp_str}{SEPARATOR}{nonce}".encode()
        expected_sig = hmac.new(coordinator_secret, payload, hashlib.sha256).hexdigest()
        if not hmac.compare_digest(expected_sig, sig_hex):
            return False, "invalid signature"

        if nonce_store is not None:
            if not nonce_store.check_and_add(nonce):
                return False, "nonce already used (replay)"

        return True, ""

    @staticmethod
    def safe_team_view(
        team_id: str,
        epoch: int,
        member_ids: list[str],
        team_partition_revision: int = 0,
    ) -> dict:
        """Return a safe team view without secrets, tokens, or credentials.

        This is the ONLY projection of team data that enters Environment State
        or HTTP response bodies.
        """
        return {
            "team_id": team_id,
            "epoch": epoch,
            "members": sorted(member_ids),
            "team_partition_revision": team_partition_revision,
        }


#: Viewer role derived from an authenticated principal (Phase 4).
VIEWER_ROLE_COORDINATOR = "coordinator"
VIEWER_ROLE_WORKER = "worker"


def derive_environment_state_principal(
    coordinator_secret: bytes | None,
    worker_task_id: str,
    proof: str,
    *,
    nonce_store: UsedNonceStore | None = None,
) -> tuple[bool, str, dict]:
    """Derive a task-bound principal for ``/environment-state``.

    The proof is bound to the **server-issued, opaque ``worker_task_id``** (the
    A2A task id the coordinator assigned when dispatching to this worker), NOT
    to a caller-selected worker id.  The shared-secret HMAC only provides
    freshness + replay protection; the caller's identity is derived by the
    route from ``resolve_worker_task(worker_task_id)``.  A secret holder cannot
    mint a proof for a task id they were never dispatched, so this binds the
    request to the actual worker.

    Returns ``(ok, reason, {viewer_role, worker_task_id})``.
    """
    if not coordinator_secret:
        return False, "coordinator_secret is empty", {}
    if not worker_task_id:
        return False, "worker_task_id is empty", {}
    if not proof:
        return False, "proof is empty", {}
    valid, reason = TeamStatusProof.verify(
        coordinator_secret,
        proof,
        worker_task_id,
        nonce_store=nonce_store,
    )
    if not valid:
        return False, reason, {}
    return (
        True,
        "",
        {
            "viewer_role": VIEWER_ROLE_WORKER,
            "worker_task_id": worker_task_id,
        },
    )


__all__ = [
    "DEFAULT_CLOCK_SKEW_SECONDS",
    "DEFAULT_MAX_AGE_SECONDS",
    "EVICTION_SLACK",
    "NONCE_BYTES",
    "SEPARATOR",
    "VIEWER_ROLE_COORDINATOR",
    "VIEWER_ROLE_WORKER",
    "TeamStatusProof",
    "UsedNonceStore",
    "derive_environment_state_principal",
]
